# Generated by Django 3.1.3 on 2020-11-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20201119_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InavilableBookingDay',
            new_name='InvalidBookingDay',
        ),
    ]
