# Generated by Django 3.1.3 on 2020-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20201119_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
