# Generated by Django 3.1.3 on 2020-11-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20201118_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='maximun_parking_lot',
            new_name='maximum_parking_lot',
        ),
    ]
