# Generated by Django 3.1.3 on 2020-11-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20201119_1004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invalidbookingday',
            table='invalid_booking_days',
        ),
    ]
