# Generated by Django 3.1.3 on 2020-11-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20201119_0426'),
        ('place', '0002_auto_20201123_0354'),
    ]

    operations = [
    ]
