# Generated by Django 3.1.3 on 2020-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20201120_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=7),
        ),
    ]
