# Generated by Django 3.1.3 on 2020-11-23 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('place', '0002_auto_20201123_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'reservation_status',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooting_members_count', models.IntegerField(default=0)),
                ('begin_datetime', models.DateTimeField()),
                ('finish_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationstatus')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
