# Generated by Django 3.1.3 on 2020-11-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0002_auto_20201118_0550'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pay_status',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooting_members_count', models.IntegerField()),
                ('begin_datetime', models.DateTimeField()),
                ('finish_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.paystatus')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
